### PR TITLE
Addition of trigger orders

### PR DESCRIPTION
**Pull request by peepopoggers**
This is a PR to add trigger orders.
I will let you know when I have tested this addition myself.

This is currently a draft because it is not ready yet and I may have made some mistakes.
Any feedback would be appreciated.

Breaking changes:

reduce_only,
ioc,
post_only,
filled_size,
remaining_size

are now all Option types

### CODE REVIEW

**Comment by peepopoggers** [comment]
@fabianboesiger Do you have a method of contact so I can ask a few questions about the module? It would help as I am stuck with some type issues / questions.

**Comment by fabianboesiger** [comment]
You could use the newly opened discussions if you want, or just ask here.

**Comment by peepopoggers** [comment]
Fixed type issues, now trigger orders should be in working condition. When I have the chance I will update this pr.

**Comment by peepopoggers** [comment]
Clippy fails but I am unsure why it wants it to be a decimal. There is only one reference to the variable.

**Comment by fabianboesiger** [comment]
Seems good to go, thanks!

**Pull request merged**
