### PR TITLE
Added the functionality to have an unauthenticated websocket

### PR DESCRIPTION
**Pull request by corvusrabus**
Background : 
- FTX websockets do not need be authenticated (i.e. signed into with an API key) for almost all of the market data. The only channels that require authentication are FILLS, ORDERS, and FTX PAY. 
- If the library is purely used to gather market data, it's desirable to not expose one's keys to it.
- New users will have an easier time testing the library if they don't need to provide their API keys to begin with.

Proposed changes:
- The connect() functions for the websocket take an Option((String,String)) to optionally provide an API/Secret key to make the websocket auhenticated (as is now the default). This breaks the existing signature of "connect".
- The WS Struct now has a variable to keep track of whether the socket is authenticated or not.
- Adjusted all tests to unauthenticated and authenticated sockets.
- Added a test for FILLS, that is expected to break for an unauthenticated socket.

### CODE REVIEW

**Review by MaxFangX — APPROVED** [review]
Looks good to me

Might need a `cargo fmt`

**Comment by fabianboesiger** [comment]
Thanks! Please run `cargo fmt` and `cargo clippy` to make sure that the checks pass.

**Comment by MaxFangX** [comment]
Re 3aa21e5: `Ws::get_response` shouldn't be public - library users should directly call `next()` which uses `get_response` internally. What's your use case for needing to access `get_response`?

(Btw the clippy errors weren't fixed, and fmt is still failing)

**Comment by corvusrabus** [comment]
Sorry, I changed Ws::next_response for my internal use and by accident pushed it to Github. I did this because the Ws::next doesn't show you which symbol the update is for. Is this intended by design? I will fix it soon.

**Comment by corvusrabus** [comment]
I removed my last commit and ran clippy as instructed. I hope it's fine now.

**Comment by corvusrabus** [comment]
I will sync it with the main when I have more time later.

The websocket updates for Ticker, Trades and Orderbooks do include the symbol, or "market" as FTX calls them. A generic response for trades has the form 

RECEIVED: {"channel": "trades", "market": "BTC-PERP", "type": "update", "data": [{"id": 1528868949, "price": 39468.0, "size": 0.0008, "side": "buy", "liquidation": false, "time": "2021-08-02T11:09:38.502354+00:00"}]}

It's just one level higher in the JSON.

**Comment by MaxFangX** [comment]
Ahh missed that, my bad.

**Comment by corvusrabus** [comment]
I merged the updates and I hope it's good now. Sorry that I missed some things in this pull request, it's my first time contributing to an open source project and I am still learning how to do it properly.

I'll open an issue later and you guys can tell me if you you'd be happy to include symbols in the market updates.

**Comment by fabianboesiger** [comment]
No worries, and thanks for your contribution!

**Pull request merged**
