### PR TITLE
fix snake case in OrderType

### LINKED ISSUE #69: Take-Profits are not working on return due to type issues
This happens when trying to initiate an order with TakeProfit order type.

Error Message:
```
Function Exited: unknown variant `take_profit`, expected one of `market`, `limit`, `stop`, `trailingStop`, `takeProfit` at line 1 column 114
```

### PR DESCRIPTION
**Pull request by dovahcrow**
fixes #69

### CODE REVIEW

**Comment by peepopoggers** [comment]
nvm i think this is a weird problem on my side

**Comment by peepopoggers** [comment]
Can confirm this is working in my project :+1:
image

**Comment by peepopoggers** [comment]
@fabianboesiger everything seems working with the ordertype for me, does this mean that using `serde alias` is okay?

**Comment by fabianboesiger** [comment]
It works for now, but we'll encounter this problem again as soon as we implement the GetOpenTriggerOrder endpoint.

**Pull request merged**
