### PR TITLE
feat(serde): derive serialization

### PR DESCRIPTION
**Pull request by matago**

### CODE REVIEW

**Comment by fabianboesiger** [comment]
Not sure why serialize would be necessary on these structs. What is your use case?

**Comment by JanSvejda** [comment]
+1. It would be, for example, useful for sending data to a file or database.

**Comment by fabianboesiger** [comment]
If someone could quickly fix this PR such that I can merge it that would be great :)

**Comment by JanSvejda** [comment]
I have the fix ready, but can't push to this branch due to permissions. Should I create a new PR?

**Comment by fabianboesiger** [comment]
Yes, please open a new PR, thanks!

**Pull request closed without merging**
