### PR TITLE
Pagination support for GetTrades and GetHistoricalPrice

### PR DESCRIPTION
**Pull request by SwayStar123**
Also changed name of Price struct to Candle, as is more fitting

### CODE REVIEW

**Comment by fabianboesiger** [comment]
Thanks, please run `cargo fmt` and `cargo clippy` such that the checks pass.

**Comment by SwayStar123** [comment]
Done

**Comment by SwayStar123** [comment]
Is there a discord or something where we can talk?

**Comment by fabianboesiger** [comment]
Thanks! You can use [GitHub Discussions](https://github.com/fabianboesiger/ftx/discussions) for discussions/questions.

**Pull request merged**
